id: IE3DB1C27
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:38:10+00:00'
last_modified: '2022-06-08T01:54:04.569244+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2548
  title: རིག་འཛིན་འགྱུར་མེད་རྡོ་རྗེའི་ལོ་རྒྱུས་ཆུ་ཟླའི་སྣང་བརྙན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F22C:
      image_group_id: I1CZ2725
      title: ''
      total_pages: 138
      order: 1
      base_file: F22C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
