id: P004554
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:27.064379
source_metadata:
  id: bdr:W1CZ2548
  title: རིག་འཛིན་འགྱུར་མེད་རྡོ་རྗེའི་ལོ་རྒྱུས་ཆུ་ཟླའི་སྣང་བརྙན
  author: ''
  volumes:
    f5317af47c734f96b9d22d309aecf9c9:
      image_group_id: I1CZ2725
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
